custom-hierarchy-cmp/force-app/main/default/objects/Custom_Hierarchy_Setting__mdt/Custom_Hierarchy_Setting__mdt.object-meta.xml
<CustomObject>
    <label>Custom Hierarchy Setting</label>
    <pluralLabel>Custom Hierarchy Settings</pluralLabel>
</CustomObject>

custom-hierarchy-cmp/force-app/main/default/objects/Custom_Hierarchy_Setting__mdt/fields/fieldName__c.field-meta.xml
<CustomField>
    <fullName>fieldName__c</fullName>
    <label>fieldName</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

custom-hierarchy-cmp/force-app/main/default/objects/Custom_Hierarchy_Setting__mdt/fields/label__c.field-meta.xml
<CustomField>
    <fullName>label__c</fullName>
    <label>label</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

custom-hierarchy-cmp/force-app/main/default/objects/Custom_Hierarchy_Setting__mdt/fields/object__c.field-meta.xml
<CustomField>
    <fullName>object__c</fullName>
    <label>object</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

custom-hierarchy-cmp/force-app/main/default/objects/Custom_Hierarchy_Setting__mdt/fields/type__c.field-meta.xml
<CustomField>
    <fullName>type__c</fullName>
    <label>type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>action</fullName>
                <default>true</default>
                <label>action</label>
            </value>
            <value>
                <fullName>boolean</fullName>
            </value>
            <value>
                <fullName>button</fullName>
            </value>
            <value>
                <fullName>button-icon</fullName>
            </value>
            <value>
                <fullName>currency</fullName>
            </value>
            <value>
                <fullName>date</fullName>
            </value>
            <value>
                <fullName>date-local</fullName>
            </value>
            <value>
                <fullName>email</fullName>
            </value>
            <value>
                <fullName>location</fullName>
            </value>
            <value>
                <fullName>number</fullName>
            </value>
            <value>
                <fullName>percent</fullName>
            </value>
            <value>
                <fullName>phone</fullName>
            </value>
            <value>
                <fullName>text</fullName>
            </value>
            <value>
                <fullName>url</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

custom-hierarchy-cmp/force-app/main/default/classes/CustomHierarchyDataService.cls
/*******************************************************************************************
* @Name         CustomHierarchyDataService 
* @Author       Kimberly Small
* @Date         01/22/2023
* @Description  This class contains all data service methods for customHierarchyCmp.
*******************************************************************************************/
public with sharing class CustomHierarchyDataService {

    /**
     * @description retrieve records required to build the hierarchy based on values provided by the user
     * @param obj object records should be pulled from
     * @param filterField field used to filter and limit the amount of records returned
     * @param filterFieldValue value from the current record that should be used for filtering
     * @param lookupField lookup field used to build the hierarchy 
     */
    @AuraEnabled(cacheable=true)
    public static List<sObject> getRecords(String obj, String filterField, String filterFieldValue, String lookupField){
        try {
            //use the fields defined in the custom hierarchy settings to build the query
            List<Custom_Hierarchy_Setting__mdt> custHierSetting = getCustomHierarchySettings(obj);

            Set<String> fields = new Set<String>();

            //add the fields to a set, ensuring no duplicate fields
            for(Custom_Hierarchy_Setting__mdt setting : custHierSetting) {
                fields.add(setting.fieldName__c);
            }
            fields.add(lookupField);

            String joinedFields = String.join(new List<String>(fields), ', ');
            String query = 'SELECT Id, ' + joinedFields + ' FROM ' + obj; 
            
            //make filter field optional
            if(String.isNotEmpty(filterField)) {
                query += ' WHERE ' + filterField + ' = :filterFieldValue';
            }

            query += ' WITH SECURITY_ENFORCED';

            List<sObject> records = Database.query(query);

            return records;
        } catch (Exception e) {
            System.debug(e.getMessage());
            throw new AuraHandledException(e.getMessage());
        }
    }

    /**
     * @description retrieve custom metadata settings to populate tree-grid columns
     * @param obj object the custom metadata settings should be pulled for
     */
    @AuraEnabled(cacheable=true) @TestVisible
    public static List<Custom_Hierarchy_Setting__mdt> getCustomHierarchySettings(String obj){
        try {
            Custom_Hierarchy_Setting__mdt[] custHierSetting = [SELECT label__c, type__c, fieldName__c FROM Custom_Hierarchy_Setting__mdt WHERE object__c = :obj];
            return custHierSetting;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
}